import React, { useState } from 'react';
import { 
  X, 
  Database, 
  Wifi, 
  AlertTriangle, 
  CheckCircle2, 
  Copy, 
  Check, 
  RefreshCw, 
  ExternalLink,
  Server,
  Users
} from 'lucide-react';

export default function ConnectionModal({
  isOpen,
  onClose,
  backendType = 'supabase',
  wsConnected = false,
  customerSource = 'fallback',
  onRefresh
}) {
  const [copied, setCopied] = useState(false);
  const [checking, setChecking] = useState(false);

  if (!isOpen) return null;

  const sqlScript = `-- 1. Buat tabel customers (CRM Penumpang)
CREATE TABLE IF NOT EXISTS customers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  phone TEXT UNIQUE NOT NULL,
  name TEXT NOT NULL,
  email TEXT,
  city TEXT DEFAULT '',
  id_card TEXT DEFAULT '',
  auth_method TEXT DEFAULT 'phone',
  is_vip BOOLEAN DEFAULT FALSE,
  is_blacklisted BOOLEAN DEFAULT FALSE,
  notes TEXT DEFAULT '',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Migrasi kolom jika tabel customers sudah ada sebelumnya
ALTER TABLE customers ADD COLUMN IF NOT EXISTS city TEXT DEFAULT '';
ALTER TABLE customers ADD COLUMN IF NOT EXISTS id_card TEXT DEFAULT '';

CREATE INDEX IF NOT EXISTS idx_customers_phone ON customers(phone);

-- 2. Aktifkan Row Level Security (RLS) & Realtime
ALTER TABLE customers ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public read customers" ON customers FOR SELECT USING (true);
CREATE POLICY "Public manage customers" ON customers FOR ALL USING (true);

ALTER PUBLICATION supabase_realtime ADD TABLE customers;

-- 3. Backfill otomatis data pelanggan dari riwayat pesanan yang sudah ada
INSERT INTO customers (phone, name, email, auth_method, created_at, updated_at)
SELECT customer_phone, customer_name, customer_email, auth_method, MIN(created_at), MIN(created_at)
FROM bookings
WHERE customer_phone IS NOT NULL AND customer_phone != ''
GROUP BY customer_phone, customer_name, customer_email, auth_method
ON CONFLICT (phone) DO NOTHING;`;

  const handleCopy = () => {
    navigator.clipboard.writeText(sqlScript);
    setCopied(true);
    setTimeout(() => setCopied(false), 2500);
  };

  const handleRecheck = async () => {
    setChecking(true);
    if (onRefresh) {
      await onRefresh();
    }
    setTimeout(() => setChecking(false), 800);
  };

  const isFallback = customerSource === 'fallback';

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-3 sm:p-4 bg-black/60 backdrop-blur-xs overflow-y-auto animate-in fade-in duration-200">
      <div className="bg-white border border-slate-200 rounded-2xl sm:rounded-3xl w-full max-w-2xl max-h-[92vh] flex flex-col shadow-2xl overflow-hidden my-auto">
        
        {/* Header */}
        <div className="p-4 sm:p-5 bg-gradient-to-r from-slate-900 to-indigo-950 text-white flex items-center justify-between shrink-0">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 rounded-xl bg-blue-600/30 border border-blue-500/40 flex items-center justify-center text-blue-300 shrink-0">
              <Database className="w-5 h-5" />
            </div>
            <div>
              <h2 className="text-base sm:text-lg font-bold">Status Koneksi & Database Backend</h2>
              <p className="text-xs text-slate-300">
                Informasi sinkronisasi data Supabase Cloud, Realtime, dan Mode Fallback
              </p>
            </div>
          </div>
          <button
            onClick={onClose}
            className="p-1.5 sm:p-2 rounded-xl text-slate-300 hover:text-white hover:bg-white/10 transition cursor-pointer shrink-0"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Modal Body */}
        <div className="p-4 sm:p-6 overflow-y-auto space-y-4 sm:space-y-5 flex-1 bg-slate-50/50 text-slate-800">
          
          {/* Status Metric Grid */}
          <div className="grid grid-cols-1 sm:grid-cols-3 gap-3">
            
            {/* 1. Database Target */}
            <div className="p-3.5 rounded-2xl bg-white border border-slate-200 shadow-2xs">
              <div className="flex items-center justify-between">
                <span className="text-[11px] font-bold text-slate-500 uppercase tracking-wider flex items-center gap-1.5">
                  <Server className="w-3.5 h-3.5 text-blue-600" />
                  Target Backend
                </span>
                <span className="w-2 h-2 rounded-full bg-emerald-500 animate-pulse"></span>
              </div>
              <p className="text-sm font-bold text-slate-800 mt-1.5">
                {backendType === 'supabase' ? 'Supabase Cloud' : 'Express REST API'}
              </p>
              <span className="text-[11px] text-slate-500 mt-0.5 block">
                {backendType === 'supabase' ? 'PostgreSQL Cloud Database' : 'SQLite Local Server'}
              </span>
            </div>

            {/* 2. Realtime Engine */}
            <div className="p-3.5 rounded-2xl bg-white border border-slate-200 shadow-2xs">
              <div className="flex items-center justify-between">
                <span className="text-[11px] font-bold text-slate-500 uppercase tracking-wider flex items-center gap-1.5">
                  <Wifi className="w-3.5 h-3.5 text-indigo-600" />
                  Status Realtime
                </span>
                <span className={`w-2 h-2 rounded-full ${wsConnected ? 'bg-emerald-500 animate-pulse' : 'bg-red-500'}`}></span>
              </div>
              <p className="text-sm font-bold text-slate-800 mt-1.5">
                {wsConnected ? 'Terhubung (Live)' : 'Terputus...'}
              </p>
              <span className="text-[11px] text-slate-500 mt-0.5 block">
                {backendType === 'supabase' ? 'Postgres Changes Channel' : 'WebSocket Server Port 5000'}
              </span>
            </div>

            {/* 3. CRM Customers Data Source */}
            <div className="p-3.5 rounded-2xl bg-white border border-slate-200 shadow-2xs">
              <div className="flex items-center justify-between">
                <span className="text-[11px] font-bold text-slate-500 uppercase tracking-wider flex items-center gap-1.5">
                  <Users className="w-3.5 h-3.5 text-amber-600" />
                  Data Pelanggan
                </span>
                <span className={`w-2 h-2 rounded-full ${isFallback ? 'bg-amber-500' : 'bg-emerald-500 animate-pulse'}`}></span>
              </div>
              <p className={`text-sm font-bold mt-1.5 ${isFallback ? 'text-amber-700' : 'text-emerald-700'}`}>
                {isFallback ? 'Mode Fallback' : 'Supabase Cloud'}
              </p>
              <span className="text-[11px] text-slate-500 mt-0.5 block">
                {isFallback ? 'Derivasi dari Tiket Pesanan' : 'Tabel customers Aktif'}
              </span>
            </div>

          </div>

          {/* Fallback Notice Banner */}
          {isFallback ? (
            <div className="p-4 rounded-2xl bg-amber-50 border border-amber-200 text-amber-900 space-y-2">
              <div className="flex items-center gap-2">
                <AlertTriangle className="w-4 h-4 text-amber-600 shrink-0" />
                <h4 className="text-xs font-bold uppercase tracking-wider">
                  Sedang Menggunakan Response Fallback
                </h4>
              </div>
              <p className="text-xs text-amber-800 leading-relaxed">
                Aplikasi saat ini membaca data pelanggan dengan <strong>menghitung riwayat tiket pesanan</strong> secara dinamis karena tabel <code>customers</code> belum dibuat di Supabase Anda.
              </p>
              <p className="text-xs text-amber-800 leading-relaxed">
                Perubahan status <strong>VIP</strong>, <strong>No-Show</strong>, dan <strong>Catatan Operator</strong> tetap aman tersimpan di browser ini. Agar tersimpan permanen di cloud Supabase untuk seluruh operator, jalankan script SQL di bawah ini.
              </p>
            </div>
          ) : (
            <div className="p-4 rounded-2xl bg-emerald-50 border border-emerald-200 text-emerald-900 space-y-1">
              <div className="flex items-center gap-2">
                <CheckCircle2 className="w-4 h-4 text-emerald-600 shrink-0" />
                <h4 className="text-xs font-bold uppercase tracking-wider">
                  Tersambung Penuh ke Database Supabase Cloud
                </h4>
              </div>
              <p className="text-xs text-emerald-800 leading-relaxed">
                Tabel <code>customers</code> aktif dan tersinkronisasi. Semua pembaruan status VIP dan catatan operator tersimpan langsung ke database cloud Supabase secara real-time.
              </p>
            </div>
          )}

          {/* SQL Setup Guide (Shown when in fallback or as reference) */}
          <div className="p-4 rounded-2xl bg-white border border-slate-200 space-y-3 shadow-2xs">
            <div className="flex items-center justify-between flex-wrap gap-2">
              <div>
                <h4 className="text-xs font-bold text-slate-800 uppercase tracking-wider">
                  Script SQL Tabel Customers Supabase
                </h4>
                <p className="text-[11px] text-slate-500 mt-0.5">
                  Jalankan di <strong>Supabase Dashboard &gt; SQL Editor &gt; New Query &gt; Run</strong>
                </p>
              </div>

              <div className="flex items-center gap-2">
                <button
                  onClick={handleCopy}
                  className={`px-3 py-1.5 rounded-xl text-xs font-bold flex items-center gap-1.5 transition cursor-pointer shadow-xs ${
                    copied 
                      ? 'bg-emerald-600 text-white' 
                      : 'bg-blue-600 hover:bg-blue-500 text-white'
                  }`}
                >
                  {copied ? (
                    <>
                      <Check className="w-3.5 h-3.5" />
                      <span>Tersalin!</span>
                    </>
                  ) : (
                    <>
                      <Copy className="w-3.5 h-3.5" />
                      <span>Salin SQL Script</span>
                    </>
                  )}
                </button>
              </div>
            </div>

            <div className="relative">
              <pre className="p-3.5 rounded-xl bg-slate-900 text-slate-200 font-mono text-[11px] overflow-x-auto max-h-48 leading-relaxed border border-slate-800">
                {sqlScript}
              </pre>
            </div>

            <div className="flex items-center justify-between pt-1">
              <a
                href="https://supabase.com/dashboard"
                target="_blank"
                rel="noopener noreferrer"
                className="text-xs font-semibold text-blue-600 hover:text-blue-700 flex items-center gap-1"
              >
                <span>Buka Supabase Dashboard</span>
                <ExternalLink className="w-3 h-3" />
              </a>

              <button
                onClick={handleRecheck}
                disabled={checking}
                className="px-3 py-1.5 rounded-xl bg-slate-100 hover:bg-slate-200 text-slate-700 text-xs font-semibold flex items-center gap-1.5 transition cursor-pointer disabled:opacity-50"
              >
                <RefreshCw className={`w-3.5 h-3.5 ${checking ? 'animate-spin text-blue-600' : 'text-slate-500'}`} />
                <span>{checking ? 'Memeriksa...' : 'Cek Ulang Status'}</span>
              </button>
            </div>
          </div>

        </div>

        {/* Footer */}
        <div className="p-3.5 sm:p-4 bg-slate-50 border-t border-slate-200 flex justify-end shrink-0">
          <button
            onClick={onClose}
            className="px-4 py-2 rounded-xl bg-slate-200 hover:bg-slate-300 text-slate-700 text-xs font-semibold transition cursor-pointer"
          >
            Tutup
          </button>
        </div>

      </div>
    </div>
  );
}
