-- ==============================================================================
-- ANTARPOOL TRAVEL & RENTAL - SUPABASE SCHEMA & INITIAL SEEDING
-- ==============================================================================
-- Run this in your Supabase project's SQL Editor (Dashboard -> SQL Editor -> New Query)

-- 1. POOLING SPOTS TABLE
CREATE TABLE IF NOT EXISTS pooling_spots (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  city TEXT NOT NULL,
  address TEXT NOT NULL,
  phone TEXT,
  landmark TEXT,
  is_active INTEGER DEFAULT 1,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. ARMADAS (FLEET & CABIN LAYOUTS) TABLE
CREATE TABLE IF NOT EXISTS armadas (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  license_plate TEXT,
  rows_count INTEGER NOT NULL,
  cols_count INTEGER NOT NULL,
  layout_json JSONB NOT NULL,
  total_seats INTEGER NOT NULL,
  is_active INTEGER DEFAULT 1,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. SCHEDULES TABLE
CREATE TABLE IF NOT EXISTS schedules (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  origin_spot_id BIGINT REFERENCES pooling_spots(id) ON DELETE CASCADE,
  destination_spot_id BIGINT REFERENCES pooling_spots(id) ON DELETE CASCADE,
  departure_time TEXT NOT NULL,
  price INTEGER NOT NULL,
  total_seats INTEGER DEFAULT 10,
  armada_id BIGINT REFERENCES armadas(id) ON DELETE SET NULL,
  vehicle_model TEXT DEFAULT 'Toyota HiAce Premio',
  vehicle_layout JSONB,
  is_active INTEGER DEFAULT 1,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. BOOKINGS TABLE
CREATE TABLE IF NOT EXISTS bookings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  booking_code TEXT UNIQUE NOT NULL,
  schedule_id BIGINT REFERENCES schedules(id) ON DELETE CASCADE,
  travel_date TEXT NOT NULL,
  customer_name TEXT NOT NULL,
  customer_phone TEXT,
  customer_email TEXT,
  auth_method TEXT DEFAULT 'phone',
  seat_numbers JSONB NOT NULL,
  seats_count INTEGER NOT NULL,
  price_per_seat INTEGER NOT NULL,
  total_price INTEGER NOT NULL,
  payment_method TEXT DEFAULT 'Bayar di Tempat (Pool)',
  payment_status TEXT DEFAULT 'PENDING',
  booking_status TEXT DEFAULT 'CONFIRMED',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. ORDER TIMELINE EVENTS (AUDIT TRAIL)
CREATE TABLE IF NOT EXISTS order_timeline_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  booking_id BIGINT REFERENCES bookings(id) ON DELETE CASCADE,
  booking_code TEXT NOT NULL,
  event_type TEXT NOT NULL, -- 'ORDER_PLACED', 'PAYMENT_RECEIVED', 'PASSENGER_CHECKED_IN', 'ORDER_CANCELLED'
  actor_role TEXT NOT NULL DEFAULT 'CUSTOMER', -- 'CUSTOMER', 'OPERATOR', 'SYSTEM'
  description TEXT NOT NULL,
  details_json JSONB,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ==============================================================================
-- ENABLE SUPABASE REALTIME REPLICATION (For Live Voice Alerts & Order Dispatch)
-- ==============================================================================
ALTER PUBLICATION supabase_realtime ADD TABLE bookings;
ALTER PUBLICATION supabase_realtime ADD TABLE schedules;
ALTER PUBLICATION supabase_realtime ADD TABLE order_timeline_events;

-- Enable Row Level Security (RLS) with open public policies for prototype
ALTER TABLE pooling_spots ENABLE ROW LEVEL SECURITY;
ALTER TABLE armadas ENABLE ROW LEVEL SECURITY;
ALTER TABLE schedules ENABLE ROW LEVEL SECURITY;
ALTER TABLE bookings ENABLE ROW LEVEL SECURITY;
ALTER TABLE order_timeline_events ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public read spots" ON pooling_spots FOR SELECT USING (true);
CREATE POLICY "Public manage spots" ON pooling_spots FOR ALL USING (true);

CREATE POLICY "Public read armadas" ON armadas FOR SELECT USING (true);
CREATE POLICY "Public manage armadas" ON armadas FOR ALL USING (true);

CREATE POLICY "Public read schedules" ON schedules FOR SELECT USING (true);
CREATE POLICY "Public manage schedules" ON schedules FOR ALL USING (true);

CREATE POLICY "Public read bookings" ON bookings FOR SELECT USING (true);
CREATE POLICY "Public insert bookings" ON bookings FOR INSERT WITH CHECK (true);
CREATE POLICY "Public update bookings" ON bookings FOR UPDATE USING (true);
CREATE POLICY "Public delete bookings" ON bookings FOR DELETE USING (true);

CREATE POLICY "Public read timeline" ON order_timeline_events FOR SELECT USING (true);
CREATE POLICY "Public manage timeline" ON order_timeline_events FOR ALL USING (true);

-- ==============================================================================
-- SEED INITIAL DATA (Pools, Armadas, Schedules)
-- ==============================================================================

-- 1. Pooling Spots
INSERT INTO pooling_spots (name, city, address, phone, landmark)
VALUES 
  ('Pool Surabaya', 'Surabaya', 'Jl. Basuki Rahmat No. 12, Tegalsari, Surabaya', '+62 811-3000-001', 'Dekat Tunjungan Plaza'),
  ('Pool Malang', 'Malang', 'Jl. Ijen No. 45, Klojen, Malang', '+62 811-3000-002', 'Dekat Bundaran Simpang Balapan')
ON CONFLICT DO NOTHING;

-- 2. Armadas (HiAce & Innova)
INSERT INTO armadas (name, license_plate, rows_count, cols_count, layout_json, total_seats)
VALUES
  (
    'Toyota HiAce Premio (10 Seat)',
    'L 7788 AB',
    4,
    3,
    '[
      [{"type":"driver","label":"Supir"},{"type":"empty","label":""},{"type":"seat","label":"1A"}],
      [{"type":"seat","label":"2A"},{"type":"aisle","label":"Lorong"},{"type":"seat","label":"2B"}],
      [{"type":"seat","label":"3A"},{"type":"aisle","label":"Lorong"},{"type":"seat","label":"3B"}],
      [{"type":"seat","label":"4A"},{"type":"seat","label":"4B"},{"type":"seat","label":"4C"}]
    ]'::jsonb,
    8
  ),
  (
    'Toyota Innova Reborn (6 Seat)',
    'N 1234 XY',
    3,
    3,
    '[
      [{"type":"driver","label":"Supir"},{"type":"empty","label":""},{"type":"seat","label":"1A"}],
      [{"type":"seat","label":"2A"},{"type":"aisle","label":"Lorong"},{"type":"seat","label":"2B"}],
      [{"type":"seat","label":"3A"},{"type":"seat","label":"3B"},{"type":"seat","label":"3C"}]
    ]'::jsonb,
    6
  )
ON CONFLICT DO NOTHING;

-- 3. Initial Schedules
DO $$
DECLARE
  v_surabaya_id BIGINT;
  v_malang_id BIGINT;
  v_armada_id BIGINT;
  v_layout JSONB;
BEGIN
  SELECT id INTO v_surabaya_id FROM pooling_spots WHERE city = 'Surabaya' LIMIT 1;
  SELECT id INTO v_malang_id FROM pooling_spots WHERE city = 'Malang' LIMIT 1;
  SELECT id, layout_json INTO v_armada_id, v_layout FROM armadas WHERE name LIKE 'Toyota HiAce%' LIMIT 1;

  IF NOT EXISTS (SELECT 1 FROM schedules) THEN
    -- Surabaya -> Malang
    INSERT INTO schedules (origin_spot_id, destination_spot_id, departure_time, price, total_seats, armada_id, vehicle_model, vehicle_layout, is_active)
    VALUES
      (v_surabaya_id, v_malang_id, '06:00', 95000, 8, v_armada_id, 'Toyota HiAce Premio', v_layout, 1),
      (v_surabaya_id, v_malang_id, '08:30', 100000, 8, v_armada_id, 'Toyota HiAce Premio', v_layout, 1),
      (v_surabaya_id, v_malang_id, '11:00', 95000, 8, v_armada_id, 'Toyota HiAce Premio', v_layout, 1),
      (v_surabaya_id, v_malang_id, '14:00', 95000, 8, v_armada_id, 'Toyota HiAce Premio', v_layout, 1),
      (v_surabaya_id, v_malang_id, '16:30', 110000, 8, v_armada_id, 'Toyota HiAce Premio', v_layout, 1),
      (v_surabaya_id, v_malang_id, '19:00', 110000, 8, v_armada_id, 'Toyota HiAce Premio', v_layout, 1),
      (v_surabaya_id, v_malang_id, '21:30', 100000, 8, v_armada_id, 'Toyota HiAce Premio', v_layout, 1),

    -- Malang -> Surabaya
      (v_malang_id, v_surabaya_id, '05:30', 95000, 8, v_armada_id, 'Toyota HiAce Premio', v_layout, 1),
      (v_malang_id, v_surabaya_id, '08:00', 100000, 8, v_armada_id, 'Toyota HiAce Premio', v_layout, 1),
      (v_malang_id, v_surabaya_id, '10:30', 95000, 8, v_armada_id, 'Toyota HiAce Premio', v_layout, 1),
      (v_malang_id, v_surabaya_id, '13:30', 95000, 8, v_armada_id, 'Toyota HiAce Premio', v_layout, 1),
      (v_malang_id, v_surabaya_id, '16:00', 110000, 8, v_armada_id, 'Toyota HiAce Premio', v_layout, 1),
      (v_malang_id, v_surabaya_id, '18:30', 110000, 8, v_armada_id, 'Toyota HiAce Premio', v_layout, 1),
      (v_malang_id, v_surabaya_id, '21:00', 100000, 8, v_armada_id, 'Toyota HiAce Premio', v_layout, 1);
  END IF;
END $$;
